ND-About-cmp
nicorithner/ckc_website pull request #7
Opened 2021-02-11 22:32 UTC by npdarrington

# About Component

- Created a new component called Header.
- Display additional information about Colorado Kettlebell Club.
- As more information is added, the page will expand as needed (dynamic scaling).

# Additional Information

- I can change the sizing so that it does not try to fill the entire screen space for a user when there is not as much information. This design was implemented based on the wireframe. Let me know if you would like me to keep it this way, or have the About Component only fill up the space it needs without taking up the full screen.

<img width="1390" alt="Screen Shot 2021-02-11 at 3 28 09 PM" src="https://user-images.githubusercontent.com/59422609/107706626-d8dce880-6c7d-11eb-8580-fb34997e1825.png">

2021-02-11 22:38 UTC, nicorithner requested changes
@npdarrington Can the content be centered in the section?

2021-02-11 23:00 UTC, npdarrington commented
Thank you Nico! I have now adjusted the styling to the screenshot shown below.

<img width="1439" alt="Screen Shot 2021-02-11 at 3 59 21 PM" src="https://user-images.githubusercontent.com/59422609/107709302-35420700-6c82-11eb-88d5-3ea1be88de1d.png">

2021-02-12 00:48 UTC, npdarrington commented
Adjust styling to only fit what is necessary based on the content, with additional spacing at the top and bottom. If more content is added, the section will grow to adjust and fit the current style accordingly. This screenshot shows the entire height of the section, as opposed to the other screenshots above that show the full screen.

<img width="1437" alt="Screen Shot 2021-02-11 at 5 44 14 PM" src="https://user-images.githubusercontent.com/59422609/107717582-34fd3800-6c91-11eb-96e4-4ae70d7d7b57.png">

2021-02-12 15:39 UTC, nicorithner approved these changes

2021-02-12 15:44 UTC, EHale64 approved these changes

2021-02-12 15:48 UTC, merged